# This file was generated by gensources.sh
# DO NOT EDIT THIS FILE MANUALLY

SRCS += autorun.c
SRCS += change_entry.c
SRCS += copy.c
SRCS += daemon/DaemonServer.cpp
SRCS += daemon/daemonize.c
SRCS += daemon/DaemonServer.cpp
SRCS += daemon/main.c
SRCS += daemon/start.s
SRCS += main.c
SRCS += std/syscall.c
SRCS += std/write.c
