#!/usr/bin/env bash

SRCS_MK=${1:-sources.mk}
shift
SRC_DIRS=$*
if [ -z "$SRC_DIRS" ]; then
	SRC_DIRS=src
fi

echo "# This file was generated by gensources.sh" > $SRCS_MK
echo "# DO NOT EDIT THIS FILE MANUALLY" >> $SRCS_MK

echo >> $SRCS_MK

for dir in $(echo $SRC_DIRS | sort); do
	for file in $(\find $dir -type f \( -name '*.cc' -o -name '*.cpp' \) | LC_ALL=C sort); do
		without_prefix=${file#$dir/}
		if [[ $file == *.inc.* ]]; then
			continue
		fi
		echo "SRCS += $without_prefix" >> $SRCS_MK
	done
  for dir in $(\find $dir -type d | sort); do
    echo "SRC_DIRS += $dir" >> $SRCS_MK
  done
done
