# This file was generated by gensources.sh
# DO NOT EDIT THIS FILE MANUALLY

SRCS += daemon/Tintin_reporter.cpp
SRCS += daemon/commands.cc
SRCS += daemon/daemonize.cc
SRCS += daemon/main.cc
SRCS += daemon/qio.cc
SRCS += daemon/run.cc
SRCS += daemon/server.cc
SRCS += hash.cc
SRCS += main.cc
SRCS += shield/autorun.cc
SRCS += shield/copy.cc
SRCS += shield/flip_bit.cc
SRCS += shield/path_check.cc
SRCS += string/kr_strappend.cc
SRCS += string/kr_strclr.cc
SRCS += string/kr_strcmp.cc
SRCS += string/kr_strcspn.cc
SRCS += string/kr_strdel.cc
SRCS += string/kr_strgrow.cc
SRCS += string/kr_strnew.cc
SRCS += string/kr_strsubst.cc
SRC_DIRS += src
SRC_DIRS += src/daemon
SRC_DIRS += src/daemon/cmds
SRC_DIRS += src/shield
SRC_DIRS += src/string
